---
- hosts: loadbalancers
  gather_facts: false
  become: true
  become_method: sudo
  roles:
    - common
    - loadbalancer

- hosts: webservers
  gather_facts: false
  become: true
  become_method: sudo
  roles:
    - common
    - webserver

- hosts: controller
  gather_facts: false
  tags:
    - testrunner
  roles:
    - testrunner