---
- name: write our nginx.conf
  template: src=nginx.conf dest=/etc/nginx/nginx.conf
  notify: Restart Nginx

- name: write our /etc/nginx/sites-available/default
  template: src=default-site dest=/etc/nginx/sites-available/default
  notify: Restart Nginx

- name: deploy website 
  template: src=index.html dest=/usr/share/nginx/html/index.html

- name: enable configuration
  file: >
    dest=/etc/nginx/sites-enabled/default
    src=/etc/nginx/sites-available/default
    state=link